// frontend-react/src/components/Header/Header.jsx
import React from "react";
import "./Header.css";
import Navigation from "./Navigation/Navigation";
import Welcome from "./Welcome/Welcome";
import Filter from "./Filter/Filter";

function Header({
    header_title, icon, welcome_needed, filter_needed
}) {
    return (
        <div className="header__container">
            <div className="navigation__container">
                <Navigation nav_title={header_title} nav_icon={icon} />
            </div>
            <div className="welcome-and-filter__container">
                {welcome_needed && <Welcome />}
                {filter_needed && <Filter />}
            </div>

        </div>
    );
}
export default Header;

// frontend-angular/src/app/components/header/header.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  @Input() header_title!:string | undefined;
  @Input() header_icon!:string | undefined;
  @Input() welcome_needed!:boolean | undefined;
  @Input() filter_needed!:boolean | undefined;

  @Input() searchText_header:string | undefined;
  @Output() searchText_headerChange = new EventEmitter();


  constructor() { }

  ngOnInit(): void {
  }

  change(newValue:string) {
    this.searchText_header = newValue;
    this.searchText_headerChange.emit(newValue);
  }

}

<div class="header__container">
    <div class="navigation__container">
        <app-navigation [nav_title]="header_title" [nav_icon]="header_icon"></app-navigation>
    </div>
    
    <div class="welcome-and-filter__container">
        <app-welcome *ngIf="welcome_needed"></app-welcome>
        <app-filter *ngIf="filter_needed" [(searchText)]="searchText_header" [(ngModel)]="searchText_header"
        (ngModelChange)="change($event)" ngDefaultControl></app-filter>
    </div>
    
</div>
