// frontend-react/src/components/ReloadRepoListButton/ReloadRepoListButton.jsx
import React from "react";
import {Link} from "react-router-dom";
import "./ReloadRepoListButton.css";
import img_replay_white_svg from "../../images/ReloadRepoListButton/replay_white.svg";

function ReloadRepoListButton(){
    return (
        <Link className="reload-repo-list-button__button" to={"../list"}>
            <img src={img_replay_white_svg} alt="reload-repo-list-white-icon" className="reload-repo-list-button__button--icon" />
        </Link>
    );
}
export default ReloadRepoListButton;

// frontend-angular/src/app/components/reload-repolist-button/reload-repolist-button.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-reload-repolist-button',
  templateUrl: './reload-repolist-button.component.html',
  styleUrls: ['./reload-repolist-button.component.css']
})
export class ReloadRepolistButtonComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="reload-repo-list-button__button">
    <a routerLink="/list">
        <img src="../../../assets/images/ReloadRepoListButton/replay_white.svg" alt="reload-repo-list-white-icon" class="reload-repo-list-button__button--icon" />
    </a>
</div>
