// frontend-angular/src/app/components/create-repo/create-repo.component.ts
import { Component, OnInit } from '@angular/core';
import { RepolistService } from '../../services/repolist.service';
import { RepoItem } from '../../models';
import { FormBuilder } from '@angular/forms';



@Component({
  selector: 'app-create-repo',
  templateUrl: './create-repo.component.html',
  styleUrls: ['./create-repo.component.css'],
})
export class CreateRepoComponent implements OnInit {
  repoItem = new RepoItem();
  title: string = "New Repository";
  icon: string = "../../../assets/images/HeaderIcons/close_white.svg";
  
  SUCCESS_REQUEST = 'Repository created successfully';
  ERROR_REQUEST = 'Request failed';
  ERROR_SERVER = 'Server error';
  ERROR_UNKNOWN = 'Unknown error';
  
  createRepoForm = this.fb.group({
    name: [''],
    description: [''],
    homepage: [''],
    has_issues: [false],
    has_projects: [false],
    has_wiki: [false],
    private: [false],
  });

  feedback: string = '';

  constructor(
    private repoListService: RepolistService,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {}

  createRepo() {
    this.repoItem = this.createRepoForm.value;
    this.repoListService
      .createRepoItem(this.repoItem, localStorage.getItem('pat')!)
      .subscribe((repo) => {
        if (repo >= 200 && repo < 300) {
          this.feedback = this.SUCCESS_REQUEST;
        } else if (repo >= 400 && repo < 500) {
          this.feedback = this.ERROR_REQUEST;
        } else if (repo >= 500 && repo < 600) {
          this.feedback = this.ERROR_SERVER;
        } else {
          this.feedback = this.ERROR_UNKNOWN;
        }
      });

    this.createRepoForm.reset();
  }

  resetFeedback() {
    this.feedback = '';
  }
}

<app-header [header_title]="title" [header_icon]="icon"></app-header>
<app-errorstate
  *ngIf="
    feedback === ERROR_REQUEST ||
      feedback === ERROR_SERVER ||
      feedback === ERROR_UNKNOWN;
    else elseBlock
  "
  [errorMessage]="feedback"
></app-errorstate>
<ng-template #elseBlock>
  <div class="createRepo__container">
    <form
      class="createRepo__form"
      [formGroup]="createRepoForm"
      (ngSubmit)="createRepo()"
      ngNativeValidate
    >
      <label for="name" class="createRepo__form--label-input">Name</label>
      <input
        type="text"
        name="name"
        class="createRepo__form--input-field"
        id="name"
        formControlName="name"
        required
      />

      <label for="description" class="createRepo__form--label-input"
        >Description</label
      >
      <textarea
        name="description"
        class="createRepo__form--input-field textarea"
        id="description"
        formControlName="description"
      ></textarea>

      <label for="home" class="createRepo__form--label-input">Home</label>
      <input
        type="text"
        name="home"
        class="createRepo__form--input-field"
        id="home"
        formControlName="homepage"
      />

      <div class="createRepo__form--checkbox-align">
        <label class="createRepo__form--label-checkbox">Has issues</label>
        <div class="createRepo__form--checkbox-item">
          <input
            type="checkbox"
            name="hasIssues"
            class="createRepo__checkboxQ--style"
            id="issues"
            formControlName="has_issues"
          />
          <label for="issues" class="switch"></label>
        </div>
      </div>

      <div class="createRepo__form--checkbox-align">
        <label class="createRepo__form--label-checkbox">Has projects</label>
        <div class="createRepo__form--checkbox-item">
          <input
            type="checkbox"
            name="hasProjects"
            class="createRepo__checkboxQ--style"
            id="projects"
            formControlName="has_projects"
          />
          <label for="projects" class="switch"></label>
        </div>
      </div>

      <div class="createRepo__form--checkbox-align">
        <label class="createRepo__form--label-checkbox">Has wiki</label>
        <div class="createRepo__form--checkbox-item">
          <input
            type="checkbox"
            name="hasWiki"
            class="createRepo__checkboxQ--style"
            id="wiki"
            formControlName="has_wiki"
          />
          <label for="wiki" class="switch"></label>
        </div>
      </div>

      <div class="createRepo__form--checkbox-align">
        <label class="createRepo__form--label-checkbox">Private</label>
        <div class="createRepo__form--checkbox-item">
          <input
            type="checkbox"
            name="isPrivate"
            class="createRepo__checkboxQ--style"
            id="private"
            formControlName="private"
          />
          <label for="private" class="switch"></label>
        </div>
      </div>
      <div *ngIf="feedback === SUCCESS_REQUEST" class="message">
        <p>{{ feedback }}</p>
        <span (click)="resetFeedback()" class="closebtn">&times;</span>
      </div>
      <button type="submit" class="create-btn">CREATE</button>
    </form>
  </div>
</ng-template>

// frontend-react/src/components/CreateRepo/CreateRepo.jsx
import React, { useState, useEffect, useRef } from "react";
import {
  createRepo,
  resetError,
  resetMessage,
} from "../../redux/actions/repoActions";
import { connect } from "react-redux";
import "./CreateRepo.css";
import Header from "../Header/Header";
import ErrorState from "../ErrorState/ErrorState";
import messageTypes from "../../redux/actions/messageTypes";
import img_close from "../../images/HeaderIcons/close_white.svg";

function CreateRepo({ dispatch, token, error, message }) {
  useEffect(() => {
    return () => {
      dispatch(resetError());
    };
  }, []);

  const messageRef = useRef();

  const handleClose = () => {
    const messageClose = messageRef.current;
    messageClose.style.display = "none";
    dispatch(resetMessage());
  };

  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [home, setHome] = useState("");
  const [issues, setIssues] = useState(false);
  const [projects, setProjects] = useState(false);
  const [wiki, setWiki] = useState(false);
  const [isPrivate, setPrivate] = useState(false);

  const handleName = (event) => {
    setName(event.target.value);
  };

  const handleDescription = (event) => {
    setDescription(event.target.value);
  };

  const handleHome = (event) => {
    setHome(event.target.value);
  };

  const handleIssues = () => {
    setIssues(!issues);
  };

  const handleProjects = () => {
    setProjects(!projects);
  };

  const handleWiki = () => {
    setWiki(!wiki);
  };

  const handlePrivate = () => {
    setPrivate(!isPrivate);
  };

  const handleForm = (event) => {
    event.preventDefault();
    dispatch(
      createRepo(
        name,
        description,
        home,
        issues,
        projects,
        wiki,
        isPrivate,
        token
      )
    );
    setName("");
    setDescription("");
    setHome("");
    setIssues(false);
    setProjects(false);
    setWiki(false);
    setPrivate(false);
  };

  return (
    <div className="createRepo__container">
      <Header header_title="New repository" icon={img_close} />
      {error === messageTypes.ERROR_REQUEST ||
      error === messageTypes.SERVER_ERROR ? (
        <ErrorState errorMessage={error} />
      ) : (
        <>
          <form className="createRepo__form" onSubmit={handleForm}>
            <label for="name" className="createRepo__form--label-input">
              Name
            </label>
            <input
              type="text"
              name="name"
              className="createRepo__form--input-field"
              id="name"
              value={name}
              onChange={handleName}
              required
            />
            <label for="description" className="createRepo__form--label-input">
              Description
            </label>
            <textarea
              type="text"
              name="description"
              className="createRepo__form--input-field textarea"
              id="description"
              value={description}
              onChange={handleDescription}
            />
            <label for="home" className="createRepo__form--label-input">
              Home
            </label>
            <input
              type="text"
              name="home"
              className="createRepo__form--input-field"
              id="home"
              value={home}
              onChange={handleHome}
            />

            <div className="createRepo__form--checkbox-align">
              <label className="createRepo__form--label-checkbox">
                Has issues
              </label>
              <div className="createRepo__form--checkbox-item">
                <input
                  type="checkbox"
                  name="hasIssues"
                  className="createRepo__checkboxQ--style"
                  id="issues"
                  checked={issues}
                  onChange={handleIssues}
                />
                <label for="issues" className="switch"></label>
              </div>
            </div>

            <div className="createRepo__form--checkbox-align">
              <label className="createRepo__form--label-checkbox">
                Has projects
              </label>
              <div className="createRepo__form--checkbox-item">
                <input
                  type="checkbox"
                  name="hasProjects"
                  className="createRepo__checkboxQ--style"
                  id="projects"
                  checked={projects}
                  onChange={handleProjects}
                />
                <label for="projects" className="switch"></label>
              </div>
            </div>

            <div className="createRepo__form--checkbox-align">
              <label className="createRepo__form--label-checkbox">
                Has wiki
              </label>
              <div className="createRepo__form--checkbox-item">
                <input
                  type="checkbox"
                  name="hasWiki"
                  className="createRepo__checkboxQ--style"
                  id="wiki"
                  checked={wiki}
                  onChange={handleWiki}
                />
                <label for="wiki" className="switch"></label>
              </div>
            </div>

            <div className="createRepo__form--checkbox-align">
              <label className="createRepo__form--label-checkbox">
                Private
              </label>
              <div className="createRepo__form--checkbox-item">
                <input
                  type="checkbox"
                  name="isPrivate"
                  className="createRepo__checkboxQ--style"
                  id="private"
                  checked={isPrivate}
                  onChange={handlePrivate}
                />
                <label for="private" className="switch"></label>
              </div>
            </div>

            <input type="submit" value="CREATE" />
          </form>
          {message === messageTypes.REQUEST_SUCCESS ? (
            <div ref={messageRef} className="message">
              <span className="closebtn" onClick={handleClose}>
                &times;
              </span>
              {message}
            </div>
          ) : null}
        </>
      )}
    </div>
  );
}

function mapStateToProps({ userReducer, repoListReducer }) {
  return {
    token: userReducer.token,
    error: repoListReducer.error,
    message: repoListReducer.message,
  };
}

export default connect(mapStateToProps)(CreateRepo);
