// frontend-react/src/components/Header/Navigation/Navigation.jsx
import React from "react";
import "./Navigation.css";
import { useHistory } from "react-router-dom";

function Navigation({
    nav_title,
    nav_icon
}) {

    const history = useHistory();

    const handleNavigation = () => {
        history.goBack();
      };

    return (
        <div className="navigation-elements__container">
            {nav_icon && <img className="navigation__img" src={nav_icon} alt="navigation-icon" onClick={handleNavigation} />}
            <p className="navigation__title">{nav_title}</p>
        </div>
    );
}
export default Navigation;

// frontend-angular/src/app/components/navigation/navigation.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Location } from '@angular/common'

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.css']
})
export class NavigationComponent implements OnInit {

  @Input() nav_title!:string | undefined;
  @Input() nav_icon!:string | undefined;


  constructor(private location: Location) { }

  ngOnInit(): void {
  }

  goBack(): void {
    this.location.back()
  }

}

<div class="navigation-elements__container">
    <img *ngIf="nav_icon" class="navigation__img" src="{{nav_icon}}" alt="navigation-icon" (click)="goBack()" />
    <p class="navigation__title">{{nav_title}}</p>
</div>
