// frontend-angular/src/app/components/welcome/welcome.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from 'src/app/models';

@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.css']
})
export class WelcomeComponent implements OnInit {
  user!:User;

  constructor() { }

  ngOnInit(): void {
    this.user = JSON.parse(localStorage.getItem('user')!);
  }

}

<div class="welcome-elements__container">
    <p class="welcome__text">
      Welcome back 
      <a class="profile__link" routerLink="/profile">
          {{user.login}}
      </a>
      !
    </p>
    <a routerLink="/profile">
      <img
        class="welcome__img"
        src="../../../assets/images/HeaderIcons/profile_white.svg"
        alt="profile-icon"
      />
    </a>
  </div>

// frontend-react/src/components/Header/Welcome/Welcome.jsx
import React from "react";
import "./Welcome.css";
import { Link } from "react-router-dom";
import { connect } from "react-redux";
import img_profile_white from "../../../images/HeaderIcons/profile_white.svg";

function Welcome({ user }) {
  return (
    <div className="welcome-elements__container">
      <p className="welcome__text">
        Welcome back{" "}
        {
          <Link className="profile__link" to={"../../profile"}>
            {user?.login}
          </Link>
        }
        !
      </p>
      <Link className="profile__link" to={"../../profile"}>
        <img
          className="welcome__img"
          src={img_profile_white}
          alt="profile-icon"
        />
      </Link>
    </div>
  );
}

function mapStateToProps({ userReducer }) {
  return {
    user: userReducer.user,
  };
}

export default connect(mapStateToProps)(Welcome);
