// frontend-react/src/components/Profile/Profile.jsx
import React from "react";
import "./Profile.css";
import { connect } from "react-redux";
import { resetUser } from "../../redux/actions/userActions";
import Header from "../Header/Header";
import img_back from "../../images/HeaderIcons/arrow_back_white.svg";

function Profile({ dispatch, user, history }) {
  const handleLogout = (event) => {
    event.preventDefault();
    dispatch(resetUser());

    const waitMs = 2000;
    setTimeout(() => {
      history.push("/");
    }, waitMs);
  };
  return (
    <div className="profile__container">
      <Header header_title="Profile" icon={img_back} />
      {user ? (
        <>
          <img className="avatar" src={user?.avatar_url} alt="avatar" />
          <div className="profile__form">
            <label className="profile__label--text">
              Username
              <input
                type="text"
                className="profile__form--username"
                value={user?.login}
                name="username"
                readonly
              />
            </label>

            {user?.email && (
              <label className="profile__label--text">
                Email
                <input
                  type="email"
                  className="profile__form--email"
                  value={user?.email}
                  name="email"
                  readonly
                />
              </label>
            )}

            {user?.company && (
              <label className="profile__label--text">
                Company
                <input
                  type="text"
                  className="profile__form--company"
                  value={user?.company}
                  name="company"
                  readonly
                />
              </label>
            )}
          </div>
          <button
            type="submit"
            className="profile__logout--button"
            onClick={handleLogout}
          >
            LOG OUT
          </button>
        </>
      ) : (
        <img
          src="https://media.giphy.com/media/2vq8dSxVEIjHaNltX9/giphy.gif"
          alt="see-you-gif"
          className="gif__seeyou--profile"
        />
      )}
    </div>
  );
}

function mapStateToProps({ userReducer }) {
  return {
    user: userReducer.user,
  };
}

export default connect(mapStateToProps)(Profile);

// frontend-angular/src/app/components/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from 'src/app/models';
import { Router } from '@angular/router';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {
  user!: User;
  title: string = "Profile";
  icon: string = "../../../assets/images/HeaderIcons/arrow_back_white.svg";

  constructor(private router: Router) { }

  ngOnInit(): void {
    this.user = JSON.parse(localStorage.getItem('user')!);
  }

  onLogOut() {
    localStorage.clear()
    this.router.navigate(['login']);
  }
}

<app-header [header_title]="title" [header_icon]="icon"></app-header>
<div class="profile__container">
  <img class="avatar" src="{{ user.avatar_url }}" alt="user-picture" />
  <div class="profile__form">
    <label class="profile__label--text">
      Username
      <input
        type="text"
        class="profile__form--username"
        value="{{ user.login }}"
        name="username"
        readonly
      />
    </label>
    <label *ngIf="user.email" class="profile__label--text">
      Email
      <input
        type="email"
        class="profile__form--email"
        value="{{ user.email }}"
        name="email"
        readonly
      />
    </label>
    <label *ngIf="user.company" class="profile__label--text">
      Company
      <input
        type="text"
        class="profile__form--company"
        value="{{ user.company }}"
        name="company"
        readonly
      />
    </label>
  </div>
  <button class="profile__logout--button" (click)="onLogOut()">LOG OUT</button>
</div>
