// frontend-react/src/components/Header/Filter/Filter.jsx
import React, { useState } from "react";
import "./Filter.css";
import { connect } from "react-redux";
import { filterRepo } from "../../../redux/actions/repoActions";
import img_search from "../../../images/HeaderIcons/search_white.svg";

function Filter({ dispatch, repoList }) {
  const [search, setSearch] = useState("");

  const handleFilter = (event) => {
    setSearch(event.target.value);
  };

  const handleSearch = () => {
    dispatch(filterRepo(search, repoList));
  };

  const handleKeyDown = (event) => {
    if (event.key === "Enter") {
      dispatch(filterRepo(search, repoList));
    }
  };

  return (
    <div className="filter-elements__container">
      <div className="filter__input">
        <label for="filter" className="filter__label--hidden"></label>
        <input
          type="text"
          placeholder="Search"
          name="search"
          className="filter__input--search"
          id="search"
          value={search}
          onChange={handleFilter}
          onKeyDown={handleKeyDown}
        />
      </div>

      <img
        className="filter__img"
        src={img_search}
        alt="filter-icon"
        onClick={handleSearch}
      />
    </div>
  );
}

function mapStateToProps({ repoListReducer }) {
  return {
    repoList: repoListReducer?.repoList,
  };
}

export default connect(mapStateToProps)(Filter);

// frontend-angular/src/app/components/filter/filter.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-filter',
  templateUrl: './filter.component.html',
  styleUrls: ['./filter.component.css']
})
export class FilterComponent implements OnInit {

  @Input() searchText: string | undefined;
  @Output() searchTextChange = new EventEmitter();

  change(newValue:string) {
    this.searchText = newValue;
    this.searchTextChange.emit(newValue);
  }

  constructor() { }

  ngOnInit(): void {
  }


}

<div class="filter-elements__container">
    <div class="filter__input">
      <label for="filter" class="filter__label--hidden"></label>
      <input
        type="text"
        placeholder="Search"
        name="search"
        class="filter__input--search"
        id="search"
        [(ngModel)]="searchText"
        (ngModelChange)="change($event)"
      />
    </div>

    <img
      class="filter__img"
      src="../../../assets/images/HeaderIcons/search_white.svg"
      alt="filter-icon"
    />
  </div>
