// frontend-angular/src/app/components/create-repo-button/create-repo-button.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-create-repo-button',
  templateUrl: './create-repo-button.component.html',
  styleUrls: ['./create-repo-button.component.css']
})
export class CreateRepoButtonComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="create-repo-button__button">
    <a routerLink="/createrepo">
        <img src="../../../assets/images/CreateRepoButton/add_white.svg" alt="create-repo-white-icon" class="create-repo-button__button--icon"/>
    </a>
</div>

// frontend-react/src/components/CreateRepoButton/CreateRepoButton.jsx
import React from "react";
import {Link} from "react-router-dom";
import "./CreateRepoButton.css";
import img_add_white_svg from "../../images/CreateRepoButton/add_white.svg";

function CreateRepoButton(){
    return (
        <Link className="create-repo-button__button" to={"../createrepo"}>
            <img src={img_add_white_svg} alt="create-repo-white-icon" className="create-repo-button__button--icon" />
        </Link>
    );
}
export default CreateRepoButton;
