// frontend-angular/src/app/components/repoitem/repoitem.component.ts
import { Component, OnInit, Input } from '@angular/core';
declare var require: any;

@Component({
  selector: 'app-repoitem',
  templateUrl: './repoitem.component.html',
  styleUrls: ['./repoitem.component.css']
})
export class RepoitemComponent implements OnInit {

  

  @Input() name!:string | undefined;
  @Input() updated_at!:string | undefined;
  @Input() language!:string | undefined;
  @Input() description!:string | undefined;
  @Input() open_issues!:number | undefined;
  @Input() stargazers_count!:number | undefined;


  checked:boolean=false;
  

  constructor() { }

  ngOnInit(): void {
  }

  dateFormatter(date:string){
    return new Intl.DateTimeFormat("en-GB", {
      year: "numeric",
      month: "long",
      day: "2-digit"
    }).format(new Date(date));
  }

  getLanguageColor(language:string){
    let GitHubColors = require('github-colors');
    return GitHubColors.get(language) ? GitHubColors.get(language).color : "#ffffff";
  }

  toggle(){
    this.checked=!this.checked;
  }

}

<div class="repo__card">
    <div class="repo__title--box">
      <p class="repo__title">{{name}}</p>
      <div class="repo__expand--icon">
        <label>
          <input class="toggle" type="checkbox" (click)="toggle()"/>
          <span></span>
        </label>
      </div>
    </div>
    <p class="repo__last-update">{{dateFormatter(updated_at!)}}</p>

    <div class="repo__language--container">
        <div *ngIf="language" class="repo__language--shadow">
          <div class="repo__language--color" [style.background-color]=getLanguageColor(language)></div>
          <div class="repo__language">{{language}}</div>
        </div>
    </div>

    <div *ngIf="checked" class="repo__details">

        <div class="repo__divider"></div>

        <p class="repo__details--description">{{description}}</p>

        <div class="repo__details--issues-and-stars">
          <div class="repo__details--open-issues">
            <img class="repo__open-isues--icon" src="../../../assets/images/RepoItem/warning.svg" alt="warning-icon" />
            <div class="repo__open-isues--text">Open issues</div>
            <div class="repo__open-isues--count">{{open_issues}}</div>
          </div>
          <div class="repo__details--stars">
            <img class="repo__star--icon" src="../../../assets/images/RepoItem/star.svg" alt="star-icon" />
            <div class="repo__stars--text">Stars</div>
            <div class="repo__stars--count">{{stargazers_count}}</div>
          </div>
        </div>
      </div>
  </div>

// frontend-react/src/components/RepoList/RepoItem/RepoItem.jsx
import React, {useRef} from "react";
import "./RepoItem.css";
import img_star from "../../../images/RepoItem/star.svg";
import img_warning from "../../../images/RepoItem/warning.svg";
import img_expand_more from "../../../images/RepoItem/expand_more.svg";
import img_expand_less from "../../../images/RepoItem/expand_less.svg";


function RepoItem({
  name,
  updated_at,
  language,
  description,
  open_issues,
  stargazers_count,
}) {

  const GitHubColors = require('github-colors');
  const language_color = GitHubColors.get(language) ? GitHubColors.get(language).color : "#ffffff";

  const expandRef = useRef();

  return (
    <div className="repo__card">
      <div className="repo__title--box">
        <p className="repo__title">{name}</p>
        <div className="repo__expand--icon">
          <label>
            <input class="toggle" type="checkbox" onClick={() => {
                  const dropdownDetails = expandRef.current;
                  if (dropdownDetails.style.display === 'none') {
                    dropdownDetails.style.display = 'block';
                  } else {
                    dropdownDetails.style.display = 'none';
                  }
                }}/>
            <span></span>
          </label>
        </div>
      </div>
      <p className="repo__last-update">Last updated {new Intl.DateTimeFormat("en-GB", {
        year: "numeric",
        month: "long",
        day: "2-digit"
      }).format(new Date(updated_at))}</p>


      <div className="repo__language--container">
        {language &&
        <div className="repo__language--shadow">
          <div className="repo__language--color" style={{ 'background-color': language_color }}></div>
          <div className="repo__language">{language}</div>
        </div>
        }
      </div>


      <div ref={expandRef} className="repo__details" style={{ display: 'none' }}>

        <div className="repo__divider"></div>

        <p className="repo__details--description">{description}</p>

        <div className="repo__details--issues-and-stars">
          <div className="repo__details--open-issues">
            <img className="repo__open-isues--icon" src={img_warning} alt="warning-icon" />
            <div className="repo__open-isues--text">Open issues</div>
            <div className="repo__open-isues--count">{open_issues}</div>
          </div>
          <div className="repo__details--stars">
            <img className="repo__star--icon" src={img_star} alt="star-icon" />
            <div className="repo__stars--text">Stars</div>
            <div className="repo__stars--count">{stargazers_count}</div>
          </div>
        </div>
      </div>

    </div>
  );
}

export default RepoItem;
