// frontend-angular/src/app/components/errorstate/errorstate.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-errorstate',
  templateUrl: './errorstate.component.html',
  styleUrls: ['./errorstate.component.css']
})
export class ErrorstateComponent implements OnInit {

  @Input() errorMessage!:string | undefined;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="error-state__container">
    <img src="../../../assets/images/GitHubLogos/git-error.svg" alt="github-logo-error-state" />
    <p>Error: {{errorMessage}}! Try again...</p>
    <app-reload-repolist-button></app-reload-repolist-button>
</div>

// frontend-react/src/components/ErrorState/ErrorState.jsx
import React from "react";
import "./ErrorState.css";
import img_github_svg from "../../images/GitHubLogos/git-error.svg";
import ReloadRepoListButton from "../ReloadRepoListButton/ReloadRepoListButton";

function ErrorState({errorMessage}) {
  return (
    <div className="error-state__container">
      <img src={img_github_svg} alt="github-logo-error-state" />
      <p>Error: {errorMessage}! Try again...</p>
      <ReloadRepoListButton />
    </div>
  );
}
export default ErrorState;
